Robot:
  Wheel:
    diameter: 470
    StepperMotor:
      type: "BYJ48"
      driver: "ULN2003"
    position: (50, ) # find length of robot. Position = -1/2 * length(in mm)
    pin: 22
  Wheel:
    diameter: 470
    StepperMotor:
      type: "BYJ48"
      driver: "ULN2003"
    position: (50, ) # find length of robot. Position = 1/2 * length(in mm)
    pin: 23
  Wheel:
    diameter: 470
    StepperMotor:
      type: "BYJ48"
      driver: "ULN2003"
    position: (-50, ) # find length of robot. Position = -1/2 * length(in mm)
    pin: 24
  Wheel:
    diameter: 470
    StepperMotor:
      type: "BYJ48"
      driver: "ULN2003"
    position: (-50, ) # find length of robot. Position = 1/2 * length(in mm)
    pin: 25

  board: "mega"
  Controllers: ""
    # webapp or controller

  sensors:
    Ultrasound:
      type: "HC-SR04"
      pin: [9, 10, 11, 12]
    Infrared:
      type: "Sharp 2Y0A02"
      pin: 0

